#! /bin/bash

if [ $1 == 'install' ]
then
	# XXX: This is obviously only going to work for my computer xP
	python setup.py install --prefix=~/.local
elif [ $1 == 'build' ]
then
    python setup.py build
elif [ $1 == 'clean' ]
then
	# Removes all the useless files generated by setup.py
	rm -rf build/ cuCRBM.cpp cuCRBM.egg-info/ dist/ layer.c model.c
fi

